embedding_model:
  provider: fastembed
  model_name: BAAI/bge-small-en-v1.5

retriever:
  search_type: mmr
  top_k: 10
  k : 5
  fetched_k: 20
  lambda_mult: 0.5

llm:
  groq:
    provider: groq
    model_name: llama-3.1-8b-instant
    temperature: 0.2
    max_output_tokens: 2048

  google:
    provider: google
    model_name: gemini-1.5-pro
    temperature: 0.2
    max_output_tokens: 2048

